# Generated by Django 2.0.5 on 2020-01-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_title', models.CharField(default='', max_length=50)),
                ('answer_text', models.CharField(max_length=100)),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('number_of_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(default='', max_length=50)),
                ('question_text', models.CharField(max_length=100)),
                ('is_multi_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(default='', max_length=50)),
                ('quiz_description', models.CharField(max_length=100)),
                ('quiz_difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_foreign_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_foreign_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
